# Cross-Origin Resource Sharing (CORS) Configuration
# Here you may configure your settings for cross-origin resource sharing
# or "CORS". This determines what cross-origin operations may execute
# in web browsers. You are free to adjust these settings as needed.

# This section lists the HTTP response headers that servers send back for access control
# requests as defined by the Cross-Origin Resource Sharing specification.
headers:
  allowed_methods:
  allowed_origins:
  allowed_headers:
  max_age:



