# Default Filesystem Disk

default:
  name:

# Filesystem Disk
# Here you may specify the default filesystem disk that should be used
# by CookieScript. The "local" disk, as well as a variety of cloud
# based disks are available to your application. Just store away!

disks:
 local:
  driver:
  root:
