# Services Configuration

# This file is for storing the credentials for third party services such
# as Stripe, GitHub, Facebook and others.
# This file provides a sane default location for this type of information,
# allowing packages to have a conventional place to find your various credentials.

# learn more: https://developers.facebook.com/docs/facebook-login/
facebook:
  client_id:
  client_secret:
  redirect:

# learn more: https://developer.github.com/v3/auth/
github:
  client_id:
  client_secret:
  redirect:

# learn more: https://stripe.com/docs/api
stripe:
  client_id:
  client_secret:

